name: forecast3m

on:
  workflow_dispatch:
  schedule:
    - cron: "15 6 * * *"

permissions:
  contents: write

jobs:
  run-forecast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # fuerza versiones exactas por seguridad (coinciden con requirements)
          pip install "keras==3.3.3" "tensorflow==2.17.0" "scikit-learn==1.2.2"

      - name: Run inference (download models from Release)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python forecast3m.py

      - name: Commit & push outputs (always commit)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add \
            public/predicciones.json \
            data_out/predicciones.csv \
            data_out/predicciones.json \
            public/erlang_forecast.json \
            data_out/erlang_forecast.json \
            public/last_update.json
          git commit -m "chore(forecast): actualización automática de predicciones + erlang (NN perfil horario)" --allow-empty || true
          git push
